@receipt_well_HostAddress = https://localhost:7028
@token =

GET {{receipt_well_HostAddress}}/weatherforecast/
Accept: application/json
Authorization: Bearer {{token}}

###

GET {{receipt_well_HostAddress}}/health

###

POST {{receipt_well_HostAddress}}/receipts/staging-slot
Authorization: Bearer {{token}}
Content-Type: application/json

###
